### ISSUE TITLE
ember-addon

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/list-view#160]
- [ ] basic project restructure to utilize add-on infrastructure
- [ ] blueprint generator for generating list-view and list-view-item subclasses

**Comment by mysterlune** [comment]
i've already got a shim available for this as an ember add-on. 

https://github.com/mysterlune/ember-cli-list-view

there was yet another shim started by someone else, though the setup was wrong and made it so nobody could pull dependencies, etc, which is why i started my own. i followed the pattern for registering with Bower and NPM the way @marcoow did for ember-simple-auth, etc.

while it's a bit rube-goldberg-ish, it does the trick for you to be able to do:

````
npm install
ember generate ember-cli-list-view
````

and add:

````
app.import('bower_components/ember-cli-list-view/list-view.js');
````

... do your project's Brocfile.js.

feel free to fork and pr. there's a Maintenance.md file in the project i'm using to document the process i follow for updating the package.

**Comment by jasonmit** [comment]
I think it would be best to turn this into an addon versus having a shim around it.  


We would then be able to take advantage of all the addon benefits and avoid the confusion of having a third party wrapper around it.


—

**Comment by stefanpenner** [comment]
> I think it would be best to turn this into an addon versus having a shim around it.

:+1:

**Comment by mysterlune** [comment]
makes sense. i agree the whole shim thing is a bit messy.

**Comment by mysterlune** [comment]
right on. well, please keep me in the loop when dev starts on this. i'm interested in contributing if it wouldn't add more cooks than necessary to the kitchen.

for now, when folks need to use this as a shim'd addon, there's something for them. i'm happy to pull that repo offline, off-registry when this project is addon-ified.

keep up the great work, y'allz.

**Comment by tim-evans** [comment]
closed by https://github.com/emberjs/list-view/pull/203

**Comment by tim-evans** [comment]
Wait... do you still want to handle the blueprints?

**Comment by taras** [comment]
@tim-evans I don't think we should add blueprints because views are on their way out anyway. There is no reason to create new Api that won't last long.

**Comment by tim-evans** [comment]
Cool. I'd consider this ticket closed, then.

**Comment by taras** [comment]
Close it :)
